import { Inter } from "next/font/google";
import "./globals.css";


export const metadata = {
  title: "Aqary Store",
  description: "Generated by Rockai Dev",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className="text-textColor font-mainFont bg-bgColor">
        {children}
      </body>
    </html>
  );
}
